@startuml packages
set namespaceSeparator none
package "train" as train #77AADD {
}
package "train.exporter" as train.exporter #99DDFF {
}
package "train.exporter.exporter" as train.exporter.exporter #99DDFF {
}
package "train.exporter.validator" as train.exporter.validator #99DDFF {
}
package "train.exporter.writer" as train.exporter.writer #99DDFF {
}
package "train.extractor" as train.extractor #44BB99 {
}
package "train.extractor.extractor" as train.extractor.extractor #44BB99 {
}
package "train.extractor.preprocess" as train.extractor.preprocess #44BB99 {
}
package "train.extractor.smooth_extractor" as train.extractor.smooth_extractor #44BB99 {
}
package "train.isolator" as train.isolator #BBCC33 {
}
package "train.isolator.isolator" as train.isolator.isolator #BBCC33 {
}
package "train.isolator.train_isolator" as train.isolator.train_isolator #BBCC33 {
}
package "train.offline_trainer" as train.offline_trainer #77AADD {
}
package "train.online_trainer" as train.online_trainer #77AADD {
}
package "train.pipeline" as train.pipeline #77AADD {
}
package "train.profiler" as train.profiler #AAAA00 {
}
package "train.profiler.generate_scaler" as train.profiler.generate_scaler #AAAA00 {
}
package "train.profiler.node_type_index" as train.profiler.node_type_index #AAAA00 {
}
package "train.profiler.profiler" as train.profiler.profiler #AAAA00 {
}
package "train.prom" as train.prom #EEDD88 {
}
package "train.prom.prom_query" as train.prom.prom_query #EEDD88 {
}
package "train.trainer" as train.trainer #EE8866 {
}
package "train.trainer.ExponentialRegressionTrainer" as train.trainer.ExponentialRegressionTrainer #EE8866 {
}
package "train.trainer.ExponentialRegressionTrainer.main" as train.trainer.ExponentialRegressionTrainer.main #EE8866 {
}
package "train.trainer.GradientBoostingRegressorTrainer" as train.trainer.GradientBoostingRegressorTrainer #EE8866 {
}
package "train.trainer.GradientBoostingRegressorTrainer.main" as train.trainer.GradientBoostingRegressorTrainer.main #EE8866 {
}
package "train.trainer.KNeighborsRegressorTrainer" as train.trainer.KNeighborsRegressorTrainer #EE8866 {
}
package "train.trainer.KNeighborsRegressorTrainer.main" as train.trainer.KNeighborsRegressorTrainer.main #EE8866 {
}
package "train.trainer.LinearRegressionTrainer" as train.trainer.LinearRegressionTrainer #EE8866 {
}
package "train.trainer.LinearRegressionTrainer.main" as train.trainer.LinearRegressionTrainer.main #EE8866 {
}
package "train.trainer.LogarithmicRegressionTrainer" as train.trainer.LogarithmicRegressionTrainer #EE8866 {
}
package "train.trainer.LogarithmicRegressionTrainer.main" as train.trainer.LogarithmicRegressionTrainer.main #EE8866 {
}
package "train.trainer.LogisticRegressionTrainer" as train.trainer.LogisticRegressionTrainer #EE8866 {
}
package "train.trainer.LogisticRegressionTrainer.main" as train.trainer.LogisticRegressionTrainer.main #EE8866 {
}
package "train.trainer.PolynomialRegressionTrainer" as train.trainer.PolynomialRegressionTrainer #EE8866 {
}
package "train.trainer.PolynomialRegressionTrainer.main" as train.trainer.PolynomialRegressionTrainer.main #EE8866 {
}
package "train.trainer.SGDRegressorTrainer" as train.trainer.SGDRegressorTrainer #EE8866 {
}
package "train.trainer.SGDRegressorTrainer.main" as train.trainer.SGDRegressorTrainer.main #EE8866 {
}
package "train.trainer.SVRRegressorTrainer" as train.trainer.SVRRegressorTrainer #EE8866 {
}
package "train.trainer.SVRRegressorTrainer.main" as train.trainer.SVRRegressorTrainer.main #EE8866 {
}
package "train.trainer.XGBoostTrainer" as train.trainer.XGBoostTrainer #EE8866 {
}
package "train.trainer.XGBoostTrainer.main" as train.trainer.XGBoostTrainer.main #EE8866 {
}
package "train.trainer.XgboostFitTrainer" as train.trainer.XgboostFitTrainer #EE8866 {
}
package "train.trainer.XgboostFitTrainer.main" as train.trainer.XgboostFitTrainer.main #EE8866 {
}
package "train.trainer.curvefit" as train.trainer.curvefit #EE8866 {
}
package "train.trainer.scikit" as train.trainer.scikit #EE8866 {
}
package "train.trainer.xgboost_interface" as train.trainer.xgboost_interface #EE8866 {
}
train --> train.extractor
train --> train.isolator
train --> train.pipeline
train --> train.profiler.node_type_index
train --> train.profiler.profiler
train.exporter.exporter --> train.exporter.validator
train.exporter.exporter --> train.exporter.writer
train.exporter.writer --> train.exporter.validator
train.extractor.extractor --> train.extractor.preprocess
train.extractor.smooth_extractor --> train.extractor.extractor
train.isolator.train_isolator --> train.isolator.isolator
train.offline_trainer --> train.extractor
train.offline_trainer --> train.isolator
train.offline_trainer --> train.pipeline
train.offline_trainer --> train.profiler.profiler
train.online_trainer --> train.extractor
train.online_trainer --> train.isolator
train.online_trainer --> train.pipeline
train.online_trainer --> train.profiler.profiler
train.pipeline --> train.extractor
train.pipeline --> train.isolator
train.pipeline --> train.profiler.node_type_index
train.profiler.generate_scaler --> train
train.prom --> train.prom.prom_query
train.trainer.XgboostFitTrainer.main --> train.trainer.xgboost_interface
@enduml
