FROM --platform=linux/amd64 quay.io/sustainable_computing_io/kepler_model_server_base:v0.7

WORKDIR /usr/local

RUN mkdir -p /usr/local/src
RUN mkdir -p /usr/local/resource

COPY dockerfiles/requirements.txt dockerfiles/requirements.txt
RUN pip install --no-cache-dir -r dockerfiles/requirements.txt

COPY src/estimate src/estimate
COPY src/server src/server
COPY src/train src/train
COPY src/util src/util
COPY cmd cmd
COPY config config

RUN mkdir -p tests/data
COPY tests/data/prom_output tests/data/prom_output 
COPY tests/*.py tests/

ENV GUNICORN_PORT=8107

EXPOSE ${GUNICORN_PORT}

CMD ["gunicorn", "--config", "config/gunicorn_config.py", "src.train.offline_trainer:app"]