FROM --platform=linux/amd64 quay.io/sustainable_computing_io/kepler_model_server_base:v0.7

WORKDIR /usr/local

RUN mkdir -p /usr/local/src
RUN mkdir -p /usr/local/resource

COPY dockerfiles/requirements.txt dockerfiles/requirements.txt
RUN pip install --no-cache-dir -r dockerfiles/requirements.txt

COPY src/estimate src/estimate
COPY src/server src/server
COPY src/train src/train
COPY src/util src/util
COPY cmd cmd

RUN mkdir -p tests/data
COPY tests/data/prom_output tests/data/prom_output 
COPY tests/*.py tests/

ENV PORT_MODEL_SERVER=8100
ENV PORT_ONLINE_TRAINER=8101
ENV PORT_OFFLINE_TRAINER=8102

# port for Model Server
EXPOSE ${PORT_MODEL_SERVER}
# port for Online Trainer (TODO: reserved for event-based online training)
EXPOSE ${PORT_ONLINE_TRAINER}
# port for Offline Trainer
EXPOSE ${PORT_OFFLINE_TRAINER}

# ENTRYPOINT ["python3.8", "cmd/main.py"]
#ENTRYPOINT [ "python3.8", "-u", "src/server/model_server.py" ]
CMD ["sh", "cmd/gunicorn.sh"]