# Include base requirements
FROM python:3.10-slim

WORKDIR /usr/local
RUN mkdir -p /usr/local/src \
		/usr/local/resource/profiles

COPY pyproject.toml .

# NOTE: README.md and __about__.py are referenced in pyproject.toml
# so that they are copied into the image for pip install to succeed
COPY README.md .
COPY src/__about__.py src/
RUN pip install --no-cache-dir . && \
		pip cache purge


COPY src/estimate src/estimate
COPY src/server src/server
COPY src/train src/train
COPY src/util src/util

RUN mkdir -p tests/data
COPY tests/data/prom_output tests/data/prom_output 
COPY tests/*.py tests/

# port for Model Server
EXPOSE 8100
# port for Online Trainer (TODO: reserved for event-based online training)
EXPOSE 8101
# port for Offline Trainer
EXPOSE 8102

CMD [ "python3.10", "-u", "src/server/model_server.py" ]
