# Include base requirements
FROM python:3.10-slim

WORKDIR /usr/local
RUN mkdir -p /usr/local/src \
		/usr/local/resource/profiles

COPY pyproject.toml .

# NOTE: README.md and src/../__about__.py are referenced in pyproject.toml
# so that they are copied into the image for pip install to succeed
COPY README.md .
COPY src/ src/

RUN mkdir -p tests/data
COPY tests/data/prom_output tests/data/prom_output
COPY tests/*.py tests/

RUN python -m pip install hatch
RUN hatch env create

# port for Model Server
EXPOSE 8100
# port for Online Trainer (TODO: reserved for event-based online training)
EXPOSE 8101
# port for Offline Trainer
EXPOSE 8102
