FROM --platform=linux/amd64 quay.io/sustainable_computing_io/kepler_model_server_base:v0.7

WORKDIR /usr/local

RUN mkdir -p /usr/local/src
RUN mkdir -p /usr/local/resource

RUN mkdir -p resource/profiles
COPY src/estimate src/estimate
COPY src/server src/server
COPY src/train src/train
COPY src/util src/util

RUN mkdir -p tests/data
COPY tests/data/prom_output tests/data/prom_output 
COPY tests/*.py tests/

RUN mkdir -p /mnt/models

# port for Model Server
EXPOSE 8100
# port for Online Trainer (TODO: reserved for event-based online training)
EXPOSE 8101
# port for Offline Trainer
EXPOSE 8102

CMD [ "python3.8", "-u", "src/server/model_server.py" ]
