# example-abs-train-pipeline:
#   running pipelines with all default value to train AbsPower model (rapl-sysfs, BPFOnly)
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: example-abs-train-pipeline
spec:
  timeouts:
    pipeline: 6h
    tasks: 5h50m
  workspaces:
    - name: mnt
      persistentVolumeClaim:
        claimName: task-pvc
  params:
    - name: PIPELINE_NAME
      value: AbsPowerTrainPipelineExample
    - name: OUTPUT_TYPE
      value: AbsPower
    # the below parameters are for short test run
    - name: STRESS_ARGS
      value:
        - cpu;none;none
    - name: STRESS_TIMEOUT
      value: 20
    - name: STRESS_BREAK_INTERVAL
      value: 1
    - name: IDLE_COLLECT_INTERVAL
      value: 100
    - name: CPU_FREQUENCY_ENABLED
      value: false
  pipelineRef:
    name: single-train-pipeline
