# kepler-default
#   running pipelines with all default value to train AbsPower model (rapl-sysfs, BPFOnly) with COS
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: default
spec:
  timeouts:
    pipeline: "6h"
    tasks: "5h50m"
  workspaces:
  - name: mnt
    persistentVolumeClaim:
      claimName: task-pvc
  params:
  - name: PIPELINE_NAME
    value: AbsPowerTrainPipelineExample
  - name: OUTPUT_TYPE
    value: AbsPower
  ## Uncomment the following lines for IBM Cloud COS
  # - name: COS_PROVIDER
  #   value: ibmcloud
  # - name: COS_SECRET_NAME
  #   value: ibm-cos-secret
  ## Uncomment the following lines for AWS COS
  # - name: COS_PROVIDER
  #   value: aws
  # - name: COS_SECRET_NAME
  #   value: aws-cos-secret
  pipelineRef:
    name: single-train-pipeline